// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: payinchannel.proto

package payinchannel

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Payin service

func NewPayinEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Payin service

type PayinService interface {
	QueryToExecute(ctx context.Context, in *PayinQueryToExecuteRequest, opts ...client.CallOption) (*PayinQueryToExecuteResponse, error)
	UpdatePayinStatus(ctx context.Context, in *UpdateStatusRequest, opts ...client.CallOption) (*BaseResponse, error)
}

type payinService struct {
	c    client.Client
	name string
}

func NewPayinService(name string, c client.Client) PayinService {
	return &payinService{
		c:    c,
		name: name,
	}
}

func (c *payinService) QueryToExecute(ctx context.Context, in *PayinQueryToExecuteRequest, opts ...client.CallOption) (*PayinQueryToExecuteResponse, error) {
	req := c.c.NewRequest(c.name, "Payin.QueryToExecute", in)
	out := new(PayinQueryToExecuteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payinService) UpdatePayinStatus(ctx context.Context, in *UpdateStatusRequest, opts ...client.CallOption) (*BaseResponse, error) {
	req := c.c.NewRequest(c.name, "Payin.UpdatePayinStatus", in)
	out := new(BaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Payin service

type PayinHandler interface {
	QueryToExecute(context.Context, *PayinQueryToExecuteRequest, *PayinQueryToExecuteResponse) error
	UpdatePayinStatus(context.Context, *UpdateStatusRequest, *BaseResponse) error
}

func RegisterPayinHandler(s server.Server, hdlr PayinHandler, opts ...server.HandlerOption) error {
	type payin interface {
		QueryToExecute(ctx context.Context, in *PayinQueryToExecuteRequest, out *PayinQueryToExecuteResponse) error
		UpdatePayinStatus(ctx context.Context, in *UpdateStatusRequest, out *BaseResponse) error
	}
	type Payin struct {
		payin
	}
	h := &payinHandler{hdlr}
	return s.Handle(s.NewHandler(&Payin{h}, opts...))
}

type payinHandler struct {
	PayinHandler
}

func (h *payinHandler) QueryToExecute(ctx context.Context, in *PayinQueryToExecuteRequest, out *PayinQueryToExecuteResponse) error {
	return h.PayinHandler.QueryToExecute(ctx, in, out)
}

func (h *payinHandler) UpdatePayinStatus(ctx context.Context, in *UpdateStatusRequest, out *BaseResponse) error {
	return h.PayinHandler.UpdatePayinStatus(ctx, in, out)
}
